### ISSUE TITLE
Proposition of changes to the protocol

### ISSUE THREAD

**Issue by SFulpius** [dedis/student20_pop#97]
By implementing the protocol, I found some minor mistakes. Also I have some propositions of changes.

1. The [README](https://github.com/dedis/student20_pop/blob/proto-specs/README.md) still mentions the Hex format, although now we are using base64 everywhere.
2. The [dataCreateLao.json](https://github.com/dedis/student20_pop/blob/proto-specs/query/method/message/data/dataCreateLao.json)  and [dataUpdateLao.json](https://github.com/dedis/student20_pop/blob/proto-specs/query/method/message/data/dataUpdateLao.json) files still mentions that the server should broadcast the change, although it is the organizer. The [dataStateLao.json](https://github.com/dedis/student20_pop/blob/proto-specs/query/method/message/data/dataStateLao.json) is correct on this point.
3. Same as the previous point, but in the [dataCreateMeeting.json](https://github.com/dedis/student20_pop/blob/proto-specs/query/method/message/data/dataCreateMeeting.json) and [dataStateMeeting.json](https://github.com/dedis/student20_pop/blob/proto-specs/query/method/message/data/dataStateMeeting.json) files.
4. In [dataCreateLao.json](https://github.com/dedis/student20_pop/blob/proto-specs/query/method/message/data/dataCreateLao.json), the field `last_modified` seems unnecessary to me, as it is always the same as the `creation` field.
5. [dataUpdateLao.json](https://github.com/dedis/student20_pop/blob/proto-specs/query/method/message/data/dataUpdateLao.json) does not have the LAO id field, thus we don't know which LAO the organizer want to update. I propose to include the LAO id in the update request.
6.  [dataStateMeeting.json](https://github.com/dedis/student20_pop/blob/proto-specs/query/method/message/data/dataStateMeeting.json) does not mention which message created or modified the meeting. I propose to add the `modification_id` and `modification_signatures` fields, which will work as in [dataStateLao.json](https://github.com/dedis/student20_pop/blob/proto-specs/query/method/message/data/dataStateLao.json).

Feel free to comment one or more of these points. Once everyone agree, I'll make a PR to update the protocol.
@dedis/student20_pop @pierluca @haoqianzhang @lhmerino

**Comment by haoqianzhang** [comment]
Looks fine to me.

**Comment by SFulpius** [comment]
We also have to include the public key of witnesses in  `modification_signatures` in [dataStateMeeting.json](https://github.com/dedis/student20_pop/blob/proto-specs/query/method/message/data/dataStateMeeting.json).
